// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: check.proto

package checkclient

import (
	"context"

	"hellozero/rpc/check/check"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = check.Request
	Response = check.Response

	Check interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultCheck struct {
		cli zrpc.Client
	}
)

func NewCheck(cli zrpc.Client) Check {
	return &defaultCheck{
		cli: cli,
	}
}

func (m *defaultCheck) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := check.NewCheckClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
